name: "brew-journal-db"
services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=${DB_NAME}'
      - 'MYSQL_PASSWORD=${DB_PASS}'
      - 'MYSQL_ROOT_PASSWORD=${DB_ROOT_PASS}'
      - 'MYSQL_USER=${DB_USER}'
    ports:
      - '3306:3306'
